### ISSUE TITLE
Change add identity endpoint

### ISSUE THREAD

**Issue by andrea-dintino** [dyne/zenswarm-oracle#3]
The new endpoint that the oracle needs to call for the announce is:

https://apiroom.net/api/zenswarm/zenswarm-issuer-add-identity

**Comment by matteo-cristino** [comment]
The endpoint that is needed to create a common oracle is defined in a comment in the [makefile](https://github.com/dyne/zenswarm-oracle/blob/main/Makefile#L5), that is:
```
https://apiroom.net:443/api/W3CDID/create_sandbox_zenswarm_did.chain
```
and it should be used to replace the `RR_*` variables that are present in the first four rows inside the Makefile as
```
RR_PORT := 443
RR_HOST := apiroom.net
RR_SCHEMA := https
RR_API := W3CDID/create_sandbox_zenswarm_did.chain
```
Maybe this can be added to the readme, will do it!
